# Naive Bayes

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('weather.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

X_train = X
y_train = y

## Splitting the dataset into the Training set and Test set

In [ ]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

In [ ]:
print(y_train)

## Encoding categorical data.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0, 1, 2, 3])], remainder = 'passthrough')
X_train = np.array(ct.fit_transform(X_train))
print(X_train)

[[1. 0. 0. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 1. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 1. 0. 1.]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
print(y_train)

[1 1 1 1 1 1 0 1 0 0 0 0 1 1]


## Feature Scaling

In [ ]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# # X_test = sc.transform(X_test)

In [ ]:
print(X_train)

## Training the Naive Bayes model on the Training set

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

## Predicting a new result

In [ ]:
#Predicting for: overcast, mild, normal, wind:true. 
print(classifier.predict([[1., 0., 0., 0., 0., 1., 0., 1., 0., 1.]]))

[1]


In [ ]:
#Predicting for: sunny, cool, high, wind:true.
print(classifier.predict([[0., 0., 1., 1., 0., 0., 1., 0., 0., 1.]])) 

[0]


In [ ]:
#Predicting for: rainy, hot, high, wind:true.
print(classifier.predict([[0., 1., 0., 0., 1., 0., 1., 0., 0., 1.]])) 

[0]


## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_train)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_train, y_pred)
print(cm)
accuracy_score(y_train, y_pred)

[[5 0]
 [5 4]]


0.6428571428571429